name: snack_distro
description: "Aplikasi Distributor Jajanan - SnackDistro"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Package formatting mata uang Rupiah

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # ==== Update Latihan 6 Langkah 1: daftarkan folder assets ====
  assets:
    - assets/images/
